baseURL: "https://mathieubourretsoto.github.io" 
title: Mathieu Bourret Soto
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: On-going Work
          url: /papers/
          weight: 1
        - name: Teaching
          url: /teaching/
          weight: 2
        - name: Conferences and seminars
          url: /conferencesseminars/
          weight: 3


params:
    description: "I am a 2nd year PhD student in Development Economics and my PhD research focuses on causes and consequences of violence and fear of violence. Besides, I am also interested in climate change adaptation."
    author: Mathieu Bourret Soto
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mathieu Bourret Soto
          subtitle: "I am a 2nd year PhD student in Development Economics and my PhD research focuses on causes and consequences of violence and fear of violence. Besides, I am also interested in climate change adaptation."
          imageUrl: "/pic_mathieu1x1.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Mathieu Bourret Soto
          buttons:
            - name: On-going Work
              url: /papers/
              weight: 1
            - name: Teaching
              url: /teaching/
              weight: 2
            - name: Conferences and seminars
              url: /conferencesseminars/
              weight: 3

    socialIcons:
        - name: CV
          url: /Resume_MBS.pdf
        - name: Email
          url: mailto:mathieu.bourret@u-bordeaux.fr
        - name: Location
          url: /location/
        - name: Linkedin
          url: https://www.linkedin.com/in/mathieu-bourret/
        - name: Orcid
          url: https://orcid.org/0000-0002-6090-420X
        - name: GitHub
          url: https://github.com/mathieubourretsoto

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mathieu Bourret Soto"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
